permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: thanq 
  email: thanq1@gmail.com
  link: http://thanq.me
  weibo: http://weibo.com/thanq
  github: http://github.com/thanq

# 站点信息
title: thanq的日志 
description: thanq的日志
url: http://thanq.me
#rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.png
favicon: /public/upload/gavatar/favicon.ico

# google analytics 设置

# disqus 设置

# 主题设置，自动激活某个标签
#active: 技术

# 首页除了最新文章外显示分类

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
